<?php

namespace Database\Seeders;

final class RbacSeedData
{
    public const ORGANIZATION_ID = '10000000-0000-4000-8000-000000000001';

    /** @var array<string, array{id: string, name: string, description: string}> */
    public const ROLES = [
        'system_administrator' => [
            'id' => '20000000-0000-4000-8000-000000000001',
            'name' => 'System Administrator',
            'description' => 'Administers MangroScan identities, hardware, auditing, settings, and AI infrastructure.',
        ],
        'researcher' => [
            'id' => '20000000-0000-4000-8000-000000000002',
            'name' => 'Researcher',
            'description' => 'Plans surveys, manages field collection, analyzes results, validates observations, and prepares reports.',
        ],
        'environmental_specialist' => [
            'id' => '20000000-0000-4000-8000-000000000003',
            'name' => 'Environmental Specialist',
            'description' => 'Approves missions and performs environmental review, ground-truth validation, accuracy analysis, and reporting.',
        ],
    ];

    /** @var array<string, string> */
    public const PERMISSIONS = [
        'organizations.manage' => 'Manage organizations',
        'users.manage' => 'Manage users',
        'roles.manage' => 'Manage roles',
        'permissions.manage' => 'Manage permissions',
        'sites.read' => 'Read survey sites',
        'sites.manage' => 'Manage survey sites',
        'boundaries.manage' => 'Manage site boundaries',
        'plots.manage' => 'Manage monitoring plots',
        'site_permissions.manage' => 'Manage site access permissions',
        'missions.read' => 'Read survey missions',
        'missions.create' => 'Create survey missions',
        'missions.update' => 'Update survey missions',
        'missions.approve' => 'Approve survey missions',
        'missions.complete' => 'Complete survey missions',
	'missions.delete' => 'Archive survey missions',
        'mission_team.manage' => 'Manage mission teams',
        'flights.read' => 'Read flight sessions',
        'flights.create' => 'Create flight sessions',
        'flights.update' => 'Update flight sessions',
        'flights.start' => 'Start flight sessions',
        'flights.complete' => 'Complete or fail flight sessions',
        'checklists.submit' => 'Submit flight checklists',
        'media.read' => 'Read media assets',
        'media.upload' => 'Upload media and sensor datasets',
        'media.quality_review' => 'Review media quality',
        'media.delete' => 'Delete media assets',
        'ai_services.manage' => 'Manage AI services',
        'ai_models.read' => 'Read AI models and versions',
        'ai_models.manage' => 'Manage AI models and versions',
        'processing_jobs.create' => 'Create processing jobs',
        'processing_jobs.manage' => 'Manage processing jobs',
        'results.read' => 'Read monitoring results',
        'results.export' => 'Export monitoring results',
        'maps.read' => 'Read generated maps',
        'validation.read' => 'Read validation data',
        'validation.create' => 'Create validation sessions',
        'validation.record_ground_truth' => 'Record ground-truth measurements',
        'validation.decide' => 'Record validation decisions',
        'validation.complete' => 'Complete validation sessions',
        'accuracy.recompute' => 'Recompute accuracy metrics',
        'reports.read' => 'Read monitoring reports',
        'reports.create' => 'Create monitoring reports',
        'reports.generate' => 'Generate monitoring reports',
        'reports.approve' => 'Approve monitoring reports',
        'exports.download' => 'Download generated exports',
        'settings.manage' => 'Manage application settings',
        'audit.read' => 'Read audit logs',
        'notifications.read' => 'Read notifications',
        'drones.read' => 'Read drone and attached sensor inventories',
        'drones.manage' => 'Manage drone inventory',
        'sensors.manage' => 'Manage drone sensor inventory',
        'sensor_calibrations.manage' => 'Manage sensor calibrations',
        'batteries.read' => 'Read battery inventory',
        'species.manage' => 'Manage species reference data',
        'share_links.manage' => 'Manage shareable links and expiration',
    ];

    /** @var array<string, list<string>> */
    public const ROLE_PERMISSIONS = [
        'system_administrator' => [
            'organizations.manage',
            'users.manage',
            'roles.manage',
            'permissions.manage',
            'drones.read',
            'drones.manage',
            'sensors.manage',
            'sensor_calibrations.manage',
            'ai_services.manage',
            'ai_models.read',
            'ai_models.manage',
            'settings.manage',
            'audit.read',
            'notifications.read',
        ],
        'researcher' => [
            'sites.read',
            'sites.manage',
            'boundaries.manage',
            'plots.manage',
            'site_permissions.manage',
            'missions.read',
            'missions.create',
            'missions.update',
            'missions.complete',
            'mission_team.manage',
            'flights.read',
            'flights.create',
            'flights.update',
            'flights.start',
            'flights.complete',
            'checklists.submit',
            'media.read',
            'media.upload',
            'ai_models.read',
            'processing_jobs.create',
            'processing_jobs.manage',
            'results.read',
            'results.export',
            'maps.read',
            'validation.read',
            'validation.create',
            'validation.record_ground_truth',
            'validation.decide',
            'validation.complete',
            'reports.read',
            'reports.create',
            'reports.generate',
            'exports.download',
            'notifications.read',
            'drones.read',
            'batteries.read',
            'share_links.manage',
        ],
        'environmental_specialist' => [
            'missions.read',
            'missions.approve',
            'missions.delete',
            'flights.read',
            'media.read',
            'media.quality_review',
            'results.read',
            'results.export',
            'maps.read',
            'validation.read',
            'validation.create',
            'validation.record_ground_truth',
            'validation.decide',
            'validation.complete',
            'accuracy.recompute',
            'reports.read',
            'reports.create',
            'reports.generate',
            'reports.approve',
            'exports.download',
            'notifications.read',
            'species.manage',
        ],
    ];

    /** @var array<string, array{id: string, first_name: string, last_name: string, position_title: string, role: string}> */
    public const USERS = [
        'admin@mangroscan.test' => [
            'id' => '30000000-0000-4000-8000-000000000001',
            'first_name' => 'System',
            'last_name' => 'Administrator',
            'position_title' => 'System Administrator',
            'role' => 'system_administrator',
        ],
        'researcher@mangroscan.test' => [
            'id' => '30000000-0000-4000-8000-000000000002',
            'first_name' => 'Test',
            'last_name' => 'Researcher',
            'position_title' => 'Researcher',
            'role' => 'researcher',
        ],
        'specialist@mangroscan.test' => [
            'id' => '30000000-0000-4000-8000-000000000003',
            'first_name' => 'Test',
            'last_name' => 'Environmental Specialist',
            'position_title' => 'Environmental Specialist',
            'role' => 'environmental_specialist',
        ],
    ];
}

